"""Generate Markdown calibration report for a turntable session."""

from __future__ import annotations

import json
from pathlib import Path


def _badge(quality: str) -> str:
    return {"good": "✅ Good", "warning": "⚠️ Warning", "bad": "❌ Bad"}.get(quality, quality)


def generate_report(session_root: Path) -> str:
    cal_dir = session_root / "calibration"
    session_json = session_root / "session.json"
    session = json.loads(session_json.read_text()) if session_json.exists() else {}

    lines: list[str] = [
        "# Turntable Calibration Report",
        "",
        f"**Session ID:** `{session.get('session_id', session_root.name)}`  ",
        f"**Nominal step:** {session.get('nominal_step_deg', '?')}°  ",
        f"**Frames captured:** {len(session.get('frames', []))}",
        "",
    ]

    axis_path = cal_dir / "axis_fit_report.json"
    if axis_path.exists():
        ax = json.loads(axis_path.read_text())
        lines += [
            "## Rotation Axis Fit",
            "",
            f"- **Quality:** {_badge(ax.get('quality', '?'))}",
            f"- **Poses used:** {ax.get('n_poses_used', '?')}",
            f"- **Step mean:** {ax.get('step_mean_deg', 0):.2f}°",
            f"- **Step std:** {ax.get('step_std_deg', 0):.2f}°",
            f"- **Step error vs nominal:** {ax.get('step_error_deg', 0):+.2f}°",
        ]
        if ax.get("axis_x_camera_m") is not None:
            lines += [
                f"- **Axis X (camera):** {ax['axis_x_camera_m']*1000:.1f} mm",
                f"- **Axis Y (camera):** {ax['axis_y_camera_m']*1000:.1f} mm",
                f"- **Orbit radius:** {(ax.get('radius_m') or 0)*1000:.1f} mm",
            ]
        if ax.get("axis_direction_camera") is not None:
            direction = ", ".join(f"{float(v):.6f}" for v in ax["axis_direction_camera"])
            tilt = ax.get("axis_tilt_from_camera_z_deg")
            tilt_text = f"{float(tilt):.2f}°" if tilt is not None else "?"
            lines += [
                f"- **Axis direction (camera):** [{direction}]",
                f"- **Tilt from camera Z:** {tilt_text}",
            ]
        lines += ["", f"*{ax.get('message', '')}*", ""]

    frames = session.get("frames", [])
    if frames:
        lines += [
            "## Per-Frame Summary",
            "",
            "| Angle | Status | Corners | Reproj. Error |",
            "|-------|--------|---------|---------------|",
        ]
        for f in frames:
            status = f.get("status")
            if not status:
                corners = int(f.get("n_corners") or 0)
                reproj = float(f.get("reprojection_error_px") or 0.0)
                if not f.get("charuco_ok") or corners < 4:
                    status = "bad"
                elif not f.get("pose_ok") or reproj > 2.0:
                    status = "warning"
                else:
                    status = "good"
            badge = {"good": "✅", "warning": "⚠️", "bad": "❌"}.get(status, status)
            reproj = f.get("reprojection_error_px")
            reproj_str = f"{reproj:.2f} px" if reproj else "—"
            lines.append(
                f"| {f.get('angle_deg', '?')}° | {badge} {status} "
                f"| {f.get('n_corners', '?')} | {reproj_str} |"
            )
        lines.append("")

    align_path = cal_dir / "alignment_report.json"
    if align_path.exists():
        al = json.loads(align_path.read_text())
        lines += [
            "## 2-D Alignment",
            "",
            f"- **Reference angle:** {al.get('reference_angle_deg', '?')}°",
            f"- **Pairs OK:** {al.get('n_ok', '?')} / {al.get('n_pairs', '?')}",
            "",
            "| Source angle | Matches | Reproj. Error |",
            "|-------------|---------|---------------|",
        ]
        for p in al.get("pairs", []):
            ok = "✅" if p.get("ok") else "❌"
            reproj = p.get("reprojection_error_px")
            reproj_str = f"{reproj:.2f} px" if reproj else "—"
            lines.append(
                f"| {ok} {p.get('src_angle', '?')}° → {p.get('dst_angle', '?')}° "
                f"| {p.get('n_matches', '?')} | {reproj_str} |"
            )
        lines.append("")

    lines += [
        "---",
        "_Generated by fringe_app_v2 turntable calibration pipeline._",
    ]
    return "\n".join(lines)


def write_report(session_root: Path) -> Path:
    cal_dir = session_root / "calibration"
    cal_dir.mkdir(exist_ok=True)
    text = generate_report(session_root)
    out = cal_dir / "calibration_report.md"
    out.write_text(text)
    return out
